// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ripmav/erdbeerpfoetchen/internal/user (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/user/mock/mock_repository.go -package=mock github.com/ripmav/erdbeerpfoetchen/internal/user Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	model "github.com/ripmav/erdbeerpfoetchen/internal/database/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetUserApiToken mocks base method.
func (m *MockRepository) GetUserApiToken(ctx context.Context, userName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserApiToken", ctx, userName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserApiToken indicates an expected call of GetUserApiToken.
func (mr *MockRepositoryMockRecorder) GetUserApiToken(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserApiToken", reflect.TypeOf((*MockRepository)(nil).GetUserApiToken), ctx, userName)
}

// GetUserById mocks base method.
func (m *MockRepository) GetUserById(ctx context.Context, userId uuid.UUID) (*model.StreamingUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserById", ctx, userId)
	ret0, _ := ret[0].(*model.StreamingUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserById indicates an expected call of GetUserById.
func (mr *MockRepositoryMockRecorder) GetUserById(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserById", reflect.TypeOf((*MockRepository)(nil).GetUserById), ctx, userId)
}

// GetUserByUserName mocks base method.
func (m *MockRepository) GetUserByUserName(ctx context.Context, userName string) (*model.StreamingUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUserName", ctx, userName)
	ret0, _ := ret[0].(*model.StreamingUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUserName indicates an expected call of GetUserByUserName.
func (mr *MockRepositoryMockRecorder) GetUserByUserName(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUserName", reflect.TypeOf((*MockRepository)(nil).GetUserByUserName), ctx, userName)
}
