// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ripmav/erdbeerpfoetchen/internal/collection (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/collection/mock/mock_repository.go -package=mock github.com/ripmav/erdbeerpfoetchen/internal/collection Repository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	collection "github.com/ripmav/erdbeerpfoetchen/internal/collection"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ReadCollection mocks base method.
func (m *MockRepository) ReadCollection(ctx context.Context, key, user string, streamerId uuid.UUID) (*collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCollection", ctx, key, user, streamerId)
	ret0, _ := ret[0].(*collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCollection indicates an expected call of ReadCollection.
func (mr *MockRepositoryMockRecorder) ReadCollection(ctx, key, user, streamerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCollection", reflect.TypeOf((*MockRepository)(nil).ReadCollection), ctx, key, user, streamerId)
}

// WriteCollection mocks base method.
func (m *MockRepository) WriteCollection(ctx context.Context, key, user string, streamerId uuid.UUID, arg4 *collection.Collection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCollection", ctx, key, user, streamerId, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCollection indicates an expected call of WriteCollection.
func (mr *MockRepositoryMockRecorder) WriteCollection(ctx, key, user, streamerId, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCollection", reflect.TypeOf((*MockRepository)(nil).WriteCollection), ctx, key, user, streamerId, arg4)
}
