// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ripmav/erdbeerpfoetchen/internal/handle (interfaces: AuthUserService)
//
// Generated by this command:
//
//	mockgen -destination=internal/handle/mock/mock_auth_service.go -package=mock github.com/ripmav/erdbeerpfoetchen/internal/handle AuthUserService

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/ripmav/erdbeerpfoetchen/internal/database/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthUserService is a mock of AuthUserService interface.
type MockAuthUserService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUserServiceMockRecorder
	isgomock struct{}
}

// MockAuthUserServiceMockRecorder is the mock recorder for MockAuthUserService.
type MockAuthUserServiceMockRecorder struct {
	mock *MockAuthUserService
}

// NewMockAuthUserService creates a new mock instance.
func NewMockAuthUserService(ctrl *gomock.Controller) *MockAuthUserService {
	mock := &MockAuthUserService{ctrl: ctrl}
	mock.recorder = &MockAuthUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUserService) EXPECT() *MockAuthUserServiceMockRecorder {
	return m.recorder
}

// GetUserByTwitchId mocks base method.
func (m *MockAuthUserService) GetUserByTwitchId(ctx context.Context, twitchID string) (*model.StreamingUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByTwitchId", ctx, twitchID)
	ret0, _ := ret[0].(*model.StreamingUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByTwitchId indicates an expected call of GetUserByTwitchId.
func (mr *MockAuthUserServiceMockRecorder) GetUserByTwitchId(ctx, twitchID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByTwitchId", reflect.TypeOf((*MockAuthUserService)(nil).GetUserByTwitchId), ctx, twitchID)
}

// CreateUser mocks base method.
func (m *MockAuthUserService) CreateUser(ctx context.Context, userName, twitchID string, isAdmin bool) (*model.StreamingUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userName, twitchID, isAdmin)
	ret0, _ := ret[0].(*model.StreamingUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthUserServiceMockRecorder) CreateUser(ctx, userName, twitchID, isAdmin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthUserService)(nil).CreateUser), ctx, userName, twitchID, isAdmin)
}
