// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ripmav/erdbeerpfoetchen/internal/handle (interfaces: CollectionService,UserService)
//
// Generated by this command:
//
//	mockgen -destination=internal/handle/mock/mock_services.go -package=mock github.com/ripmav/erdbeerpfoetchen/internal/handle CollectionService,UserService
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	collection "github.com/ripmav/erdbeerpfoetchen/internal/collection"
	model "github.com/ripmav/erdbeerpfoetchen/internal/database/model"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionService is a mock of CollectionService interface.
type MockCollectionService struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionServiceMockRecorder
	isgomock struct{}
}

// MockCollectionServiceMockRecorder is the mock recorder for MockCollectionService.
type MockCollectionServiceMockRecorder struct {
	mock *MockCollectionService
}

// NewMockCollectionService creates a new mock instance.
func NewMockCollectionService(ctrl *gomock.Controller) *MockCollectionService {
	mock := &MockCollectionService{ctrl: ctrl}
	mock.recorder = &MockCollectionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionService) EXPECT() *MockCollectionServiceMockRecorder {
	return m.recorder
}

// ReadCollection mocks base method.
func (m *MockCollectionService) ReadCollection(ctx context.Context, collectionKey, user string, streamerId uuid.UUID) (*collection.Collection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCollection", ctx, collectionKey, user, streamerId)
	ret0, _ := ret[0].(*collection.Collection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCollection indicates an expected call of ReadCollection.
func (mr *MockCollectionServiceMockRecorder) ReadCollection(ctx, collectionKey, user, streamerId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCollection", reflect.TypeOf((*MockCollectionService)(nil).ReadCollection), ctx, collectionKey, user, streamerId)
}

// WriteCollection mocks base method.
func (m *MockCollectionService) WriteCollection(ctx context.Context, collectionKey, user string, streamerId uuid.UUID, arg4 *collection.Collection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCollection", ctx, collectionKey, user, streamerId, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCollection indicates an expected call of WriteCollection.
func (mr *MockCollectionServiceMockRecorder) WriteCollection(ctx, collectionKey, user, streamerId, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCollection", reflect.TypeOf((*MockCollectionService)(nil).WriteCollection), ctx, collectionKey, user, streamerId, arg4)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetUserApiToken mocks base method.
func (m *MockUserService) GetUserApiToken(ctx context.Context, streamerName string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserApiToken", ctx, streamerName)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserApiToken indicates an expected call of GetUserApiToken.
func (mr *MockUserServiceMockRecorder) GetUserApiToken(ctx, streamerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserApiToken", reflect.TypeOf((*MockUserService)(nil).GetUserApiToken), ctx, streamerName)
}

// GetUserByUserName mocks base method.
func (m *MockUserService) GetUserByUserName(ctx context.Context, userName string) (*model.StreamingUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUserName", ctx, userName)
	ret0, _ := ret[0].(*model.StreamingUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUserName indicates an expected call of GetUserByUserName.
func (mr *MockUserServiceMockRecorder) GetUserByUserName(ctx, userName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUserName", reflect.TypeOf((*MockUserService)(nil).GetUserByUserName), ctx, userName)
}
