// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"encoding/json"

	"github.com/google/uuid"
)

type PfoetchenCollection struct {
	Key      string
	Streamer uuid.UUID
	Viewer   string
	Json     json.RawMessage
}

type PfoetchenUser struct {
	ID       uuid.UUID
	UserName string
	ApiToken uuid.UUID
}
