// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type StreamingCollection struct {
	CollectionKey  string
	Streamer       uuid.UUID
	Viewer         string
	Json           json.RawMessage
	CollectionType string
}

type StreamingUser struct {
	ID                 uuid.UUID
	UserName           string
	ApiToken           uuid.UUID
	RateLimitPerMinute int32
	TwitchID           sql.NullString
	IsAdmin            bool
}
