// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package model

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getCollection = `-- name: GetCollection :one
SELECT key, streamer, viewer, json FROM "streaming"."collection"
WHERE "key" = $1
AND "streamer" = $2
AND "viewer" = $3
`

type GetCollectionParams struct {
	Key      string
	Streamer uuid.UUID
	UserHash string
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (StreamingCollection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, arg.Key, arg.Streamer, arg.UserHash)
	var i StreamingCollection
	err := row.Scan(
		&i.Key,
		&i.Streamer,
		&i.Viewer,
		&i.Json,
	)
	return i, err
}

const getUserApiToken = `-- name: GetUserApiToken :one
SELECT api_token FROM "streaming"."user"
WHERE "user_name" = $1
`

func (q *Queries) GetUserApiToken(ctx context.Context, userName string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserApiToken, userName)
	var api_token uuid.UUID
	err := row.Scan(&api_token)
	return api_token, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, user_name, api_token FROM "streaming"."user"
WHERE "id" = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (StreamingUser, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i StreamingUser
	err := row.Scan(&i.ID, &i.UserName, &i.ApiToken)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, user_name, api_token FROM "streaming"."user"
WHERE "user_name" = $1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (StreamingUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, userName)
	var i StreamingUser
	err := row.Scan(&i.ID, &i.UserName, &i.ApiToken)
	return i, err
}

const getUserId = `-- name: GetUserId :one
SELECT id FROM "streaming"."user"
WHERE "user_name" = $1
`

func (q *Queries) GetUserId(ctx context.Context, userName string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserId, userName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertCollection = `-- name: UpsertCollection :exec
INSERT INTO "streaming"."collection" ("key", "streamer", "viewer", "json")
VALUES ($1, $2, $3, $4)
ON CONFLICT ("key", "streamer", "viewer")
DO UPDATE SET "json" = $4
`

type UpsertCollectionParams struct {
	Key      string
	Streamer uuid.UUID
	Viewer   string
	Json     json.RawMessage
}

func (q *Queries) UpsertCollection(ctx context.Context, arg UpsertCollectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertCollection,
		arg.Key,
		arg.Streamer,
		arg.Viewer,
		arg.Json,
	)
	return err
}
