// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package model

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getCollection = `-- name: GetCollection :one
SELECT collection_key, streamer, viewer, json, collection_type FROM "streaming"."collection"
WHERE "collection_key" = $1
AND "streamer" = $2
AND "viewer" = $3
`

type GetCollectionParams struct {
	Key      string
	Streamer uuid.UUID
	UserHash string
}

func (q *Queries) GetCollection(ctx context.Context, arg GetCollectionParams) (StreamingCollection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, arg.Key, arg.Streamer, arg.UserHash)
	var i StreamingCollection
	err := row.Scan(
		&i.CollectionKey,
		&i.Streamer,
		&i.Viewer,
		&i.Json,
		&i.CollectionType,
	)
	return i, err
}

const getUserApiToken = `-- name: GetUserApiToken :one
SELECT api_token FROM "streaming"."user"
WHERE "user_name" = $1
`

func (q *Queries) GetUserApiToken(ctx context.Context, userName string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserApiToken, userName)
	var api_token uuid.UUID
	err := row.Scan(&api_token)
	return api_token, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, user_name, api_token, rate_limit_per_minute, twitch_id, is_admin FROM "streaming"."user"
WHERE "id" = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (StreamingUser, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i StreamingUser
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.ApiToken,
		&i.RateLimitPerMinute,
		&i.TwitchID,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByUserName = `-- name: GetUserByUserName :one
SELECT id, user_name, api_token, rate_limit_per_minute, twitch_id, is_admin FROM "streaming"."user"
WHERE "user_name" = $1
`

func (q *Queries) GetUserByUserName(ctx context.Context, userName string) (StreamingUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUserName, userName)
	var i StreamingUser
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.ApiToken,
		&i.RateLimitPerMinute,
		&i.TwitchID,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByTwitchId = `-- name: GetUserByTwitchId :one
SELECT id, user_name, api_token, rate_limit_per_minute, twitch_id, is_admin FROM "streaming"."user"
WHERE "twitch_id" = $1
`

func (q *Queries) GetUserByTwitchId(ctx context.Context, twitchID string) (StreamingUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByTwitchId, twitchID)
	var i StreamingUser
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.ApiToken,
		&i.RateLimitPerMinute,
		&i.TwitchID,
		&i.IsAdmin,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO "streaming"."user" ("user_name", "twitch_id", "api_token", "rate_limit_per_minute", "is_admin")
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_name, api_token, rate_limit_per_minute, twitch_id, is_admin
`

type CreateUserParams struct {
	UserName           string
	TwitchID           string
	ApiToken           uuid.UUID
	RateLimitPerMinute int32
	IsAdmin            bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (StreamingUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.UserName,
		arg.TwitchID,
		arg.ApiToken,
		arg.RateLimitPerMinute,
		arg.IsAdmin,
	)
	var i StreamingUser
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.ApiToken,
		&i.RateLimitPerMinute,
		&i.TwitchID,
		&i.IsAdmin,
	)
	return i, err
}

const getUserId = `-- name: GetUserId :one
SELECT id FROM "streaming"."user"
WHERE "user_name" = $1
`

func (q *Queries) GetUserId(ctx context.Context, userName string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserId, userName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserRateLimit = `-- name: GetUserRateLimit :one
SELECT rate_limit_per_minute FROM "streaming"."user"
WHERE "user_name" = $1
`

func (q *Queries) GetUserRateLimit(ctx context.Context, userName string) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserRateLimit, userName)
	var rate_limit_per_minute int32
	err := row.Scan(&rate_limit_per_minute)
	return rate_limit_per_minute, err
}

const upsertCollection = `-- name: UpsertCollection :exec
INSERT INTO "streaming"."collection" ("collection_key", "streamer", "viewer", "json", "collection_type")
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT ("collection_key", "streamer", "viewer")
DO UPDATE SET "json" = $4, "collection_type" = $5
`

type UpsertCollectionParams struct {
	CollectionKey  string
	Streamer       uuid.UUID
	Viewer         string
	Json           json.RawMessage
	CollectionType string
}

func (q *Queries) UpsertCollection(ctx context.Context, arg UpsertCollectionParams) error {
	_, err := q.db.ExecContext(ctx, upsertCollection,
		arg.CollectionKey,
		arg.Streamer,
		arg.Viewer,
		arg.Json,
		arg.CollectionType,
	)
	return err
}
